name: docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - run: yarn
        working-directory: packages/radish

      - run: yarn build
        working-directory: packages/docs

      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: pages
          publish_dir: packages/docs/build
          github_token: ${{ secrets.GITHUB_TOKEN }}
